### ISSUE TITLE
Stale?

### ISSUE THREAD

**Issue by end-user** [highlightjs/highlightjs-tsql#2]
Hey, I hope this project doesn't grow stale!  It's exactly the syntax highlighting I'd like to use.  Since it would be directly applicable for Microsoft, I think this project would help drive a lot of how highlightjs works.  It appears DevOps uses highlightjs for their wiki (and other) markdown code styling, and it's lacking exactly what you've added here.  I'm hoping it can get picked up by the parent project.

**Comment by Greg-Smulko** [comment]
Hi, sorry for the late reply - I'm not even going to pretend that I have good excuses...

I'm putting some effort at the moment to bring this plugin to the more usable state. 

If you'd like to contribute, you're more than welcomed. :)
