### ISSUE TITLE
CDN Hosting

### ISSUE THREAD

**Issue by kuenzign** [highlightjs/highlightjs-tsql#9]
Is there a CDN where this is hosted at like most other highlight.js plugins?  Having a CDN that is up to date would be preferable over having to host the files yourself and ensuring they are up to date.

**Comment by joshgoebel** [comment]
I'm going to guess no since it's not mentioned in the docs.  @Greg-Smulko might know different though.

**Comment by kuenzign** [comment]
If the package is added to npm, people can use unpkg.com as a CDN (which is what several other highlight.js plugins do).  What would be the likelihood of adding the package to npm?

**Comment by joshgoebel** [comment]
That would be up to Greg since it's one more thing they'd have to personally maintain. We currently don't require that 3rd party grammars hosted here must have an npm package.

**Comment by Greg-Smulko** [comment]
Hi, I think I should be able to do so.

We have already https://www.npmjs.com/package/highlight.js-tsql, but it's not up-to-date and not mentioned in the docs. I'll try to sort it out today.

**Comment by Greg-Smulko** [comment]
Apologies, I didn't manage to acquire the credentials to deploy to that link so far. I'm starting my sabbatical next week, so I'll be able to look at this no earlier than in September. Stay tuned! 🤷

**Comment by Greg-Smulko** [comment]
Hi @kuenzign , I published it as https://www.npmjs.com/package/highlight.js-tsql.
Could you please check and report back whether it works for you just fine? Thanks in advance!

**Comment by kuenzign** [comment]
@Greg-Smulko I think you are missing the `main` entry in the package.json which is supposed to indicate the main entrypoint.

**Comment by kuenzign** [comment]
I believe I have corrected this with #11

**Comment by kuenzign** [comment]
Can confirm that unpkg.com now works properly as a CDN using this link: https://unpkg.com/highlight.js-tsql/dist/tsql.min.js
